apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudsync
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cloudsync
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cloudsync
    spec:
      containers:
      - name: cloudsync
        image: jumpstartagora.azurecr.io/contoso-supermarket/pos-cloudsync:latest
        env:
        - name: SQL_HOST
          value: {{ .Release.Name }}-contosodb
        - name: SQL_USERNAME
          value: {{ .Values.postgres.username }}
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_PASSWORD     
        - name: SQL_DATABASE
          value: "contoso"
        - name: SYNCINTERVAL
          value: '120'
        - name: COSMOSENDPOINT
          value: {{ .Values.cosmos.endpoint }}
        - name: COSMOSKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: COSMOS_KEY     
        - name: COSMOSDB
          value: {{ .Values.cosmos.database }}
        - name: COSMOSCONTAINER
          value: {{ .Values.cosmos.container }}