# Postgre SQL Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-contosodb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-contosodb
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
# Create PostgreSQL Database Container with local storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-contosodb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-contosodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-contosodb
    spec:
      containers:
      - name: contosodb
        image: postgres:15.0
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_PASSWORD      
        - name: POSTGRES_DB
          value: contoso
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgresql-vol
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-vol
          hostPath:
            path: /var/postgresql-data