apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contosopos
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contosopos
  chart:
    spec:
      chart: ./contoso_supermarket/operations/contoso_supermarket/charts/contosopos
  values:
    acr_name: agacr40ca5
    branch_name: "canary"
    image_tag: v1.2
    github_User: brauliomsft
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "pos"
      database: "contoso"
      endpoint: https://agcosmos40ca5.documents.azure.com:443/
    point_of_sale:
      title: "Contoso Supermarket"
      cameras_enabled: "False"
      cameras_url: ""
      new_category: "True"
      holiday_banner: "False"
      store_id: 2
      store_location: "Chicago"