# Default values for ovms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

storage:
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi