apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contosodb
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contosodb
  chart:
    spec:
      chart: ./contoso_supermarket/operations/contoso_supermarket/charts/contosodb
  values:
    acr_name: agacr26969
    branch_name: "dev"
    image_tag: v1.0
    github_User: __githubUser__
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "pos"
      database: "contoso"
      endpoint: https://agcosmos26969.documents.azure.com:443/
    point_of_sale:
      new_category: "True"
      holiday_banner: "False"
      store_id: 4
      store_location: "dev"
