apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsync
  namespace: contosopos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsync
  template:
    metadata:
      labels:
        app: cloudsync
    spec:
      containers:
      - name: cloudsync
        image: jumpstartagora.azurecr.io/contoso-supermarket/pos-cloudsync:latest
        env:
        - name: SQL_HOST
          value: "contosodb"
        - name: SQL_USERNAME
          value: "postgres"
        - name: SQL_PASSWORD
          value: "admin123"
        - name: SQL_DATABASE
          value: "contoso"
        - name: SYNCINTERVAL
          value: '120'
        - name: COSMOSENDPOINT
          value: ''
        - name: COSMOSKEY
          value: ''
        - name: COSMOSDB
          value: ''
        - name: COSMOSCONTAINER
          value: ''                               