apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contosopos
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contosopos
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./contoso_supermarket/operations/contoso_supermarket/charts/contosopos
  values:
    acr_name: agacrf0142
    branch_name: "production"
    image_tag: v1.0
    github_User: __githubUser__
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "pos"
      database: "contoso"
      endpoint: __cosmosEndpoint__
    point_of_sale:
      title: "Contoso Supermarket"
      new_category: "True"
      holiday_banner: "False"
      store_id: 1
      store_location: "Seattle"