apiVersion: batch/v1
kind: Job
metadata:
  name: model-downloader-job
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      containers:
      - name: model-downloader
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -O /models/ovms_config.sh https://raw.githubusercontent.com/microsoft/jumpstart-agora-apps/manufacturing/contoso_manufacturing/deployment/configs/ovms_config.sh 
          chmod +x /models/ovms_config.sh
          /models/ovms_config.sh
        volumeMounts:
        - name: models-volume
          mountPath: /models
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: ovms-pvc
      restartPolicy: Never
  backoffLimit: 0