broker:
  mqttBroker:
    image:
      repository: charrisagoracr.azurecr.io/mqtt-broker
      tag: latest
    imagePullPolicy: Always
  ports:
  - name: mqtt-broker
    port: 1883
    targetPort: 1883
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
simulator:
  mqttSimulator:
    image:
      repository: charrisagoracr.azurecr.io/mqtt-simulator
      tag: latest
    imagePullPolicy: Always
  replicas: 1
metricsExporter:
  mqtt2prom:
    image:
      repository: ghcr.io/hikhvar/mqtt2prometheus
      tag: latest
    imagePullPolicy: Always
  replicas: 1
