apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensor-monitor.fullname" . }}-mqtt2prom
  labels:
    io.kompose.service: mqtt2prom
  {{- include "sensor-monitor.labels" . | nindent 4 }}
  annotations:
    # override default path of /metrics if necessary
    prometheus.io/path: /metrics
    # set to true if you want our custom prometheus scraper job to gather custom metrics
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.mqtt2prom.type }}
  selector:
    io.kompose.service: mqtt2prom
  {{- include "sensor-monitor.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mqtt2prom.ports | toYaml | nindent 2 -}}