apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudsync
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: cloudsync
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./contoso_supermarket/operations/contoso_supermarket/charts/cloudsync
  values:
    acr_name: __acrName__
    branch_name: "canary"
    image_tag: v1.0
    github_User: __githubUser__
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "Orders"
      database: "Orders"
      endpoint: __cosmosEndpoint__