# Create Contoso Supermarket Point Of Sale Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-contosopos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-contosopos
spec:
  selector:
    app: {{ .Release.Name }}-contosopos
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-contosopos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-contosopos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-contosopos
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-contosopos
    spec:
      containers:
        - name: contosopos
          image: Agacrce99b.azurecr.io/contoso-supermarket/pos:latest
          env:
            - name: SQL_HOST
              value: {{ .Release.Name }}-contosodb
            - name: SQL_USERNAME
              value: {{ .Values.postgres.username }}
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: POSTGRES_PASSWORD      
            - name: SQL_DATABASE
              value: {{ .Values.postgres.database }}
            - name: HEAD_TITLE
              value : {{ .Values.point_of_sale.title }}
            - name: CAMERAS_ENABLED
              value: "{{ .Values.point_of_sale.cameras_enabled }}"
            - name: CAMERAS_BASEURL
              value: {{ .Values.point_of_sale.cameras_url }}
            - name: NEW_CATEGORY
              value: "{{ .Values.point_of_sale.new_category }}"
            - name: STORE_ID
              value: "{{ required "A Store ID is required!" .Values.point_of_sale.store_id }}"
            - name: STORE_LOCATION
              value: "{{ required "A Store Location is required!" .Values.point_of_sale.store_location }}"
            - name: HOLIDAY_BANNER
              value: "{{ .Values.point_of_sale.holiday_banner }}"
          ports:
            - containerPort: 5000
