# Create Contoso Supermarket AI app
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-contosoai
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-contosoai
spec:
  selector:
    app: {{ .Release.Name }}-contosoai
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-contosoai
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-contosoai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-contosoai
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-contosoai
    spec:
      containers:
        - name: contosoai
          image: {{ .Values.acr_name }}.azurecr.io/{{ .Values.branch_name}}/contoso-supermarket/contosoai:v1.0
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: acr-secret