apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql-file
data:
  initDB.sql: |-
{{ .Files.Get "files/initdb.sql" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      containers:
      - name: initdb
        image: postgres:15.0
        env:
        - name: PGHOST
          value: {{ .Release.Name }}-contosodb
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrespw
              key: POSTGRES_PASSWORD
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrespw
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        command:
          - sh
          - -c
          - psql -h $PGHOST -U $POSTGRES_USER -d $POSTGRES_DB -f /var/initdb.sql
        volumeMounts:
          - name: init-db-sql
            mountPath: /var/initdb.sql
            subPath: initDB.sql
      restartPolicy: "Never"
      volumes:
        - name: init-db-sql
          configMap:
            name: init-db-sql-file
            items:
            - key: initDB.sql
              path: initDB.sql
  dependsOn:
    - name: {{ .Release.Name }}-contosodb
      condition: "Ready"
