# Create Contoso Supermarket Queue Monitoring Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-queue-monitoring-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-backend
spec:
  selector:
    app: {{ .Release.Name }}-queue-monitoring-backend
  ports:
  - name: http
    port: 4000
    targetPort: 4000
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-queue-monitoring-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-queue-monitoring-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-queue-monitoring-backend
    spec:
      containers:
        - name: queue-monitoring-backend
          image: jumpstartagora.azurecr.io/contoso-supermarket/queue-monitoring-backend:latest
          env:
            - name: SQL_HOST
              value: {{ .Release.Name }}-contosodb
            - name: SQL_USERNAME
              value: {{ .Values.postgres.username }}
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: POSTGRES_PASSWORD
            - name: SQL_DATABASE
              value: {{ .Values.postgres.database }}
            - name: TIMEZONE
              value: {{ .Values.queue_monitoring.timezone }}
            - name: ASPNETCORE_URLS
              value : "http://*:4000/"
          ports:
            - containerPort: 4000