
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "A valid Postgress password is required!" .Values.postgres.password }}
  COSMOS_KEY: {{ required "A valid Cosmos Access Key is required! (Use '--set cosmos.access_key=\"<Cosmos Access Key>\"' )" .Values.cosmos.access_key }}