name: CI
on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main
      - staging
      - canary
      - prod

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to Azure Container Registry
        run: |
            docker tag contososupermarket:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/contososupermarket:${{github.ref_name}}
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/contososupermarket:${{github.ref_name}}            